export const API_LOGIN= "/Account/login"
export const API_GET_ALL_USER= "/Admin/GetAccountByFilter"
export const API_ACTIVE_AND_INACTIVE_USER= "/Admin/getListUserActiveAndDeactive"
export const API_PENDING_USER= "/Admin/getListUserPending"
export const API_GET_ALL_CLINIC= "/Admin/getListClinicActiveAndDeactive"
export const API_GET_CLINIC_BY_NAME= "/Admin/getClinicsByName"
export const API_GET_ALL_CLINIC_OWNER= "/Admin/GetAccountByFilter"
export const API_ADD__CLINIC_OWNER= "/Admin/addClinicOwner"
export const API_CHANGE_STATUS_USER_ACTIVE_OR_INACTIVE= "/Admin/updateStatusBetweenActiveAnDeactive"
export const API_DELETE_USER_PENDING= "/Admin/deleteUserPendingById"
export const API_CHANGE_STATUS_USER_PENDING_TO_ACTIVE= "/Admin/updateStatusPendingToActive"
export const API_GET_ALL_DOCTOR_BY_CLINIC= "/ClinicOwner/GetAllDoctorsOfClinic?clinicId="
// export const API_GET_WORKING_TIME= "/WorkingTime/getWorkingTimesByDoctorIdAndWorkingDayOfWeek?doctorId=1&workingDayOfWeek=2"
export const API_GET_WORKING_TIME_DOCTOR_BY_ID= "/WorkingTime"
export const API_CREATE_BOOKING= "/Booking/AddBooking"
export const API_GET_CLINIC_BY_ID= "/Guest/GetClinicById?id="
export const API_GET_ALL_SERVICES_OF_CLINIC= "/Guest/GetAllServicesOfClinic?id="
