export { default as Home } from './home'
export { default as Dashboard } from '../components/dashboard'
export { default as Login } from './login'
export { default as ManageUser } from './admin/manage-user'
export { default as ManageClinic } from './admin/manage-clinic'
export { default as ManageClinicOwner } from './admin/manage-clinic-owner'
